num_envs: 5
num_epochs: 20
epoch_steps: 5000
eval_interval: 1
eval_episodes: 10
model_dir: models

agent:
  exploration_strategy:
    name: "SoftmaxExploration"
    params:
      temperature: 1.0
      temperature_min: 0.1
      decay_steps: 100000
  lr: 0.0001
  gamma: 0.99
  batch_size: 32
  warmup_steps: 5000
  buffer_size: 100000
  target_update_interval: 10000
  use_double_q: true
  use_per: true