num_envs: 5
use_ray: false
num_epochs: 20
epoch_steps: 5000
eval_interval: 1
eval_episodes: 10
model_dir: dqn_models
agent_type: DQN
seed: 42

# Resources for Ray Tune trials (optional)
resources_per_trial:
  cpu: 1
  gpu: 0

env:
  continuous: false

agent:
  exploration_strategy:
    name: "SoftmaxExploration"
    params:
      temperature: 1.0
      temperature_min: 0.1
      decay_steps: 100000
  lr: 0.0001
  gamma: 0.99
  batch_size: 32
  warmup_steps: 5000
  buffer_size: 100000
  target_update_interval: 1
  use_double_q: true
  prioritized: true
