num_envs: 16
use_ray: false
num_epochs: 50
epoch_steps: 2048
eval_interval: 1
eval_episodes: 10
model_dir: ppo_models
agent_type: PPO
seed: 42

# Resources for Ray Tune trials (optional)
max_concurrent_trials: 4
resources_per_trial:
  cpu: 5
  gpu: 0.15

env:
  continuous: false

agent:
  lr: 0.0001
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.1
  update_epochs: 3
  batch_size: 256
