num_envs: 5
use_ray: false
num_epochs: 20
epoch_steps: 5000
eval_interval: 1
eval_episodes: 10
model_dir: sac_models
agent_type: SAC
seed: 42

env:
  continuous: true

agent:
  lr: 0.0003
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  batch_size: 256
  buffer_size: 100000
  warmup_steps: 1000
